# -*- coding: utf-8 -*-

APP_NAME = 'message_gateway'

REDIS_HOST_KEY = 'REDIS_HOST'
DEFAULT_REDIS_HOST = 'redis'

REDIS_PORT_KEY = 'REDIS_PORT'
DEFAULT_REDIS_PORT = 6379

MOKE_SERVER_HOST_KEY = 'MOKE_SERVER_HOST'
DEFAULT_MOKE_SERVER_HOST = 'mock-sms-server'

MOKE_SERVER_PORT_KEY = 'MOKE_SERVER_PORT'
DEFAULT_MOKE_SERVER_PORT = 8080

JSON_HEADER = {'Content-Type': 'application/json'}

WAIT_TIME = 0.1
